version : '3'

services : 
   ariproxy :
        build : 
          context : .
          args: 
            - mysqlhost=${sql-host}:3306
            - arihost=${ari-host}:8088
            - ariproxyhost=${ariproxy-host}
            - ariproxyport=8020
            - jdbcuser=root
            - jdbcpasswd=${sql-password}
            - mysqlschema=tenant1
            - ariusername=${ariuser}
            - aripassword=${aripasswd}
            - ariwshost=${arihost}
            - appName=hello-world
            - ariwsport=8088
        ports : 
        - 8020:8080  

   

