version : '3'

services : 
   ariproxy :
        build : 
          context : .
          args: 
            - mysqlhost=10.142.0.2:3306
            - arihost=35.231.176.109:8088
            - ariproxyhost=35.231.176.109
            - jdbcuser=root
            - jdbcpasswd=freaks03
            - mysqlschema=tenant1
            - ariusername=ariuser
            - aripassword=ariuser123
        ports : 
        - 8020:8080  

   

